PATCH /api/2.3/auctions/cf20406610ab4cc3899643a702abd067/awards/4749579c52b047caba3ea57106a14827?acc_token=820f7665c64b4715b82c2b7c7fa11ae5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 146
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "unsuccessful", 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "title": "Disqualified"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/cf20406610ab4cc3899643a702abd067/awards/7c528d3c18c84f05b8455e21ade03630

{
  "data": {
    "status": "unsuccessful", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Disqualification reason", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/829e77c1e2be4a5d93698a380f0a52a5?KeyID=9f82dbe0&Signature=2KwktH4QXMsyDP%2FRuduGtaGlrllvHxht2cjYDewSjEEllFkgnjG%2FgbfoVwe0UKJIZSuR7nxLY72s%252BY61Z5RmDw%253D%253D", 
        "title": "Disqualified_reason.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:27:53.895112+03:00", 
        "dateModified": "2017-05-25T17:27:53.895159+03:00", 
        "id": "3f7991e62258409cbe6ee1a62f014295"
      }
    ], 
    "description": "Candidate didn’t sign the auction protocol in 3 business days", 
    "complaintPeriod": {
      "startDate": "2017-05-25T17:27:53.600917+03:00", 
      "endDate": "2017-05-25T17:27:54.165795+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "title": "Disqualified", 
    "bid_id": "29d322a2ac9848e389e1f43a34b92ee7", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-05-25T17:27:54.187697+03:00", 
    "id": "4749579c52b047caba3ea57106a14827"
  }
}

