POST /api/2.3/auctions/cf20406610ab4cc3899643a702abd067/awards/4749579c52b047caba3ea57106a14827/documents?acc_token=820f7665c64b4715b82c2b7c7fa11ae5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 388
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/829e77c1e2be4a5d93698a380f0a52a5?KeyID=9f82dbe0&Signature=JUPWFO1JFw5wieSBNZYir6ft%2Bvl2Iolmu3%2F4yAYkFID3XM1Z2yTc9lty10Zon%2Bx0SQi4bOd02hLnJX5sGv%2FtCg%3D%3D", 
    "title": "Disqualified_reason.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/cf20406610ab4cc3899643a702abd067/awards/4749579c52b047caba3ea57106a14827/documents/3f7991e62258409cbe6ee1a62f014295

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Disqualification reason", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/829e77c1e2be4a5d93698a380f0a52a5?KeyID=9f82dbe0&Signature=2KwktH4QXMsyDP%2FRuduGtaGlrllvHxht2cjYDewSjEEllFkgnjG%2FgbfoVwe0UKJIZSuR7nxLY72s%252BY61Z5RmDw%253D%253D", 
    "title": "Disqualified_reason.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:27:53.895112+03:00", 
    "dateModified": "2017-05-25T17:27:53.895159+03:00", 
    "id": "3f7991e62258409cbe6ee1a62f014295"
  }
}

