PATCH /api/2.3/auctions/cf20406610ab4cc3899643a702abd067/awards/568ad8c6449946cba0b18727e1b19695?acc_token=820f7665c64b4715b82c2b7c7fa11ae5 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/cf20406610ab4cc3899643a702abd067/awards/4749579c52b047caba3ea57106a14827

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2017-05-25T17:27:53.129188+03:00", 
      "endDate": "2017-05-25T17:27:53.375531+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "29d322a2ac9848e389e1f43a34b92ee7", 
    "value": {
      "currency": "UAH", 
      "amount": 475.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-05-25T17:27:53.613582+03:00", 
    "id": "568ad8c6449946cba0b18727e1b19695"
  }
}

