PATCH /api/2.3/auctions/b4642b238000446da633ee7ddceaf888/bids/690fd52831fe4399b9fcfa844f6afbd1?acc_token=00d6b1c518f540678ad19d842d6e6951 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

null

