PATCH /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/cancellations/cd5555cb65f8400f858ab4dc7f069a11?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/0509de3ab1a54602add1c906cb3445ed?KeyID=561eda93&Signature=9Z8SnItvJMvdI6fCwE4nBODwjaUBPCD06c8Snrrwne%252Be8oHjLGMpQOeqzH%252BS%252BmhrcrBW2feq%252BWwd9q4f8gQYCQ%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:06.110321+03:00", 
        "dateModified": "2017-05-25T17:28:06.110369+03:00", 
        "id": "6c4ed26941c949248c3fc4f9e4bd3ff2"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Changed description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/f6a0c38db78845c48d927a6e86d9ec09?KeyID=561eda93&Signature=Cdqnbwh4aGY2Fp4gSwSwgoe7q4i99pGIPc5z8gOr7EIUBzSkg0s0IlF91fOBPCgStt4szSPuynwCFz4L7eFSDg%253D%253D", 
        "title": "Notice-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:06.110321+03:00", 
        "dateModified": "2017-05-25T17:28:06.707115+03:00", 
        "id": "6c4ed26941c949248c3fc4f9e4bd3ff2"
      }
    ], 
    "reason": "cancellation reason", 
    "date": "2017-05-25T17:28:07.324412+03:00", 
    "cancellationOf": "tender", 
    "id": "cd5555cb65f8400f858ab4dc7f069a11"
  }
}

