PATCH /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/questions/53b338e9acd24058b017ba820b6db9ed?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 162
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\""
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "description": "Просимо додати таблицю потрібної калорійності харчування", 
    "title": "Калорійність", 
    "date": "2017-05-25T17:28:01.143805+03:00", 
    "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
    "id": "53b338e9acd24058b017ba820b6db9ed", 
    "questionOf": "tender"
  }
}

