POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2096
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2017-05-25T17:32:45.012376"
    }, 
    "tenderAttempts": 1, 
    "procurementMethodType": "dgfOtherAssets", 
    "value": {
      "currency": "UAH", 
      "amount": 100
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "submissionMethodDetails": "quick", 
    "dgfDecisionDate": "2016-11-17", 
    "mode": "test", 
    "dgfDecisionID": "219560", 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "items": [
      {
        "classification": {
          "scheme": "CPV", 
          "id": "66113000-5", 
          "description": "Земельні ділянки"
        }, 
        "quantity": 5, 
        "description": "Земля для військовослужбовців", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "address": {
          "countryName": "Україна", 
          "postalCode": "79000", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова 1", 
          "locality": "м. Київ"
        }
      }
    ], 
    "dgfID": "219560"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/d547e32bff2148b0b8a3062c9fd82861

{
  "access": {
    "token": "937b4795d6ca4973a8d94e1f76f20c87"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-PS-2017-05-25-000001", 
    "enquiryPeriod": {
      "startDate": "2017-05-25T17:27:49.876374+03:00", 
      "endDate": "2017-05-25T17:31:51.147784+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "next_check": "2017-05-25T17:31:51.147784+03:00", 
    "awardCriteria": "highestCost", 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "title_en": "[TESTING] ", 
    "id": "d547e32bff2148b0b8a3062c9fd82861", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:27:49.880626+03:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2017-05-25T17:27:49.880697+03:00", 
        "id": "6bd9480631564971a36cc31733157625"
      }
    ], 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-05-25T17:27:49.885311+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-05-25T17:27:49.876374+03:00", 
      "endDate": "2017-05-25T17:31:51.147784+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-05-25T17:31:51.147784+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2017-05-25T17:27:49.876374+03:00", 
    "submissionMethodDetails": "quick", 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "35e1a262bee442e9bc9c457675d19e50", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] ", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

