GET /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents/3fbe646270544461b5a56510d60bb5bb HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "document description", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8c53267c7f2a4606ba5a4d4fc5f1d896?KeyID=561eda93&Signature=lc1h6mE2c0QkK2OQP7wknrJW0tQM77kM99qQ5TzNlM8o9wAJv%2FsiVJmVFYeAwTOU03J4CAxd%2FDv63uxjQtaJDA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:28:00.203531+03:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2017-05-25T17:28:00.203572+03:00", 
    "id": "3fbe646270544461b5a56510d60bb5bb"
  }
}

