POST /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/contracts/c711443e16b14269bcb6a28ba525d471/documents?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 351
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d76c16815b504ab9b0b1fda1ba3d99ba?KeyID=561eda93&Signature=TezkHah%2BKC0wmAUahg3j8FG3rrx4NRWnGVJBUPcpMKNHEuIleMn%2BgvKOjYx8smZP%2BcyRmbHQTYduKt7i1veABg%3D%3D", 
    "title": "contract_first_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/contracts/c711443e16b14269bcb6a28ba525d471/documents/13521a7c2d93476f96c0ec8e3b8b3feb

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d76c16815b504ab9b0b1fda1ba3d99ba?KeyID=561eda93&Signature=KL2YXgj6%2FYQpISacrmg1HkHil6Z%252Bqn%252BuooH4Hca3O9QPSxYm1utZH8VLx46pqzx%252BOMAUsEPll3HYVh1fN0WtBQ%253D%253D", 
    "title": "contract_first_document.doc", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:28:04.579796+03:00", 
    "dateModified": "2017-05-25T17:28:04.579838+03:00", 
    "id": "13521a7c2d93476f96c0ec8e3b8b3feb"
  }
}

