GET /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:27:59.570223+03:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2017-05-25T17:27:59.570283+03:00", 
      "id": "e4efbf88435a487582b4c119a5c0970c"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "document description", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8c53267c7f2a4606ba5a4d4fc5f1d896?KeyID=561eda93&Signature=lc1h6mE2c0QkK2OQP7wknrJW0tQM77kM99qQ5TzNlM8o9wAJv%2FsiVJmVFYeAwTOU03J4CAxd%2FDv63uxjQtaJDA%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:28:00.203531+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-05-25T17:28:00.203572+03:00", 
      "id": "3fbe646270544461b5a56510d60bb5bb"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/27eff7fb16b443cab36b998512ffb50b?KeyID=561eda93&Signature=CVTQ%2FDSC7ys3FfKJ3HGzCW8dYFPvWk%252Bg6iyrBpnlyPAnlPM1o1Rv2SvduJNs7T92KhmuFSwppjtHUwwNVUoVBg%253D%253D", 
      "title": "AwardCriteria.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:28:00.316280+03:00", 
      "dateModified": "2017-05-25T17:28:00.316339+03:00", 
      "id": "8de16b471d1a481d8c26ef6876e3da0b"
    }
  ]
}

