POST /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/contracts/c711443e16b14269bcb6a28ba525d471/documents?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 348
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/289f8a278eb644cb9f7d298afaae9b5c?KeyID=561eda93&Signature=6obv%2Blzy5jS4AesBHW1Jm55F5iPbAvWvkIVfmR74Y2vxOfyCxe9HS1RvaWl67aIUHzsIn3QCAwmxLlxoPycZBQ%3D%3D", 
    "title": "contract_second_document.doc", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/contracts/c711443e16b14269bcb6a28ba525d471/documents/ef780353c8004470add72739cb50fb3f

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/msword", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/289f8a278eb644cb9f7d298afaae9b5c?KeyID=561eda93&Signature=2tXeY1giwOBC8mvhDecnmMgSwm5SwuJs06ahLwgZy41ztfH5NRjEqW1IswY8K1HmxvaKvBQi%252BP167x3%252BypAaCg%253D%253D", 
    "title": "contract_second_document.doc", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:28:04.934471+03:00", 
    "dateModified": "2017-05-25T17:28:04.934526+03:00", 
    "id": "ef780353c8004470add72739cb50fb3f"
  }
}

