GET /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-PS-2017-05-25-000001", 
    "auctionUrl": "http://auction-sandbox.openprocurement.org/auctions/b0cb82074afe46c4a99deba3a188d456", 
    "enquiryPeriod": {
      "startDate": "2017-05-18T17:27:44.999643+03:00", 
      "endDate": "2017-05-25T17:27:44.999643+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "next_check": "2017-05-25T18:11:44.999643+03:00", 
    "awardCriteria": "highestCost", 
    "questions": [
      {
        "description": "Просимо додати таблицю потрібної калорійності харчування", 
        "title": "Калорійність", 
        "date": "2017-05-25T17:28:01.143805+03:00", 
        "answer": "Таблицю додано в файлі \"Kalorijnist.xslx\"", 
        "id": "53b338e9acd24058b017ba820b6db9ed", 
        "questionOf": "tender"
      }
    ], 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "id": "b0cb82074afe46c4a99deba3a188d456", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:27:59.570223+03:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2017-05-25T17:27:59.570283+03:00", 
        "id": "e4efbf88435a487582b4c119a5c0970c"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "description": "document description", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/8c53267c7f2a4606ba5a4d4fc5f1d896?KeyID=561eda93&Signature=lc1h6mE2c0QkK2OQP7wknrJW0tQM77kM99qQ5TzNlM8o9wAJv%2FsiVJmVFYeAwTOU03J4CAxd%2FDv63uxjQtaJDA%253D%253D", 
        "title": "Notice.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:00.203531+03:00", 
        "documentType": "technicalSpecifications", 
        "dateModified": "2017-05-25T17:28:00.203572+03:00", 
        "id": "3fbe646270544461b5a56510d60bb5bb"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/27eff7fb16b443cab36b998512ffb50b?KeyID=561eda93&Signature=CVTQ%2FDSC7ys3FfKJ3HGzCW8dYFPvWk%252Bg6iyrBpnlyPAnlPM1o1Rv2SvduJNs7T92KhmuFSwppjtHUwwNVUoVBg%253D%253D", 
        "title": "AwardCriteria.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:00.316280+03:00", 
        "dateModified": "2017-05-25T17:28:00.316339+03:00", 
        "id": "8de16b471d1a481d8c26ef6876e3da0b"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/pdf", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b65535c4bc074b72a60f62acb82472f4?KeyID=561eda93&Signature=QjWyizp6j1aJUgyNi0lqSP9LBTCixti9L1VNVP7mqK7TLtRxNl8ufSwa7Zygg%2Fj%252Bu99v7GHR6rykbXWCkYv7AQ%253D%253D", 
        "title": "AwardCriteria-2.pdf", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:00.316280+03:00", 
        "dateModified": "2017-05-25T17:28:00.447454+03:00", 
        "id": "8de16b471d1a481d8c26ef6876e3da0b"
      }, 
      {
        "index": 1, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "First illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e281146b2c1749f08360f1e8bdb82ba2?KeyID=561eda93&Signature=5wz2KBsPr0Izti7DjUBJsOpdiiRfPv13vZI7By3uMdxoJDLPSp%2F1xccfksXFNM1r5T%2FvLEVHHiiBG2EBX4woDA%253D%253D", 
        "title": "first_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:00.565678+03:00", 
        "documentType": "illustration", 
        "dateModified": "2017-05-25T17:28:00.565725+03:00", 
        "id": "3fd6f0ea761440ca82f5c6c002ab9779"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Second illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c6da3fd87c57460ea3e698a31a2a1aa1?KeyID=561eda93&Signature=qk0YGoVQ5GmtgBgga4GZ1Fu%252BaS3nj40gW8SvaRxRcUEnxl2iSkAfh3fHzeaCf7p0RYV5GtIbxTeTfcFMehrTDA%253D%253D", 
        "title": "second_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:00.698675+03:00", 
        "documentType": "illustration", 
        "dateModified": "2017-05-25T17:28:00.698721+03:00", 
        "id": "7ede76dd3ab94e8ca093c4ebb62ce1bd"
      }, 
      {
        "index": 2, 
        "hash": "md5:00000000000000000000000000000000", 
        "description": "Third illustration description", 
        "format": "image/jpeg", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bc4490ed8c1f4d6daa18795ea1c78208?KeyID=561eda93&Signature=OENTefhpCFK6qCBNcMY%252B%2F1gGtk1fqAUOR8wYRJdnpHRAaroDRaTtnlDr5bEJxuYz%2FJ9I46a2KmwswPifKQD%2FCg%253D%253D", 
        "title": "third_illustration.jpeg", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:00.802456+03:00", 
        "documentType": "illustration", 
        "dateModified": "2017-05-25T17:28:00.802509+03:00", 
        "id": "25e01f0d8d9d4d568ad6796c825272d3"
      }, 
      {
        "title": "Familiarization with bank asset", 
        "format": "offline/on-site-examination", 
        "accessDetails": "Familiar with asset: days, time, address", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:00.964148+03:00", 
        "documentType": "x_dgfAssetFamiliarization", 
        "dateModified": "2017-05-25T17:28:00.964194+03:00", 
        "id": "d1629a95886a4aeebab0266d3f81adf3"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-05-25T17:28:02.738662+03:00", 
    "status": "active.auction", 
    "tenderPeriod": {
      "startDate": "2017-05-18T17:27:44.999643+03:00", 
      "endDate": "2017-05-25T17:27:44.999643+03:00"
    }, 
    "auctionPeriod": {
      "startDate": "2017-05-25T17:27:44.999643+03:00", 
      "shouldStartAfter": "2017-05-26T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2017-05-25T17:27:59.569797+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "08391d0984d74b1787545029fff9485f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

