GET /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/contracts/c711443e16b14269bcb6a28ba525d471/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d76c16815b504ab9b0b1fda1ba3d99ba?KeyID=561eda93&Signature=KL2YXgj6%2FYQpISacrmg1HkHil6Z%252Bqn%252BuooH4Hca3O9QPSxYm1utZH8VLx46pqzx%252BOMAUsEPll3HYVh1fN0WtBQ%253D%253D", 
      "title": "contract_first_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:28:04.579796+03:00", 
      "dateModified": "2017-05-25T17:28:04.579838+03:00", 
      "id": "13521a7c2d93476f96c0ec8e3b8b3feb"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/msword", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/289f8a278eb644cb9f7d298afaae9b5c?KeyID=561eda93&Signature=2tXeY1giwOBC8mvhDecnmMgSwm5SwuJs06ahLwgZy41ztfH5NRjEqW1IswY8K1HmxvaKvBQi%252BP167x3%252BypAaCg%253D%253D", 
      "title": "contract_second_document.doc", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:28:04.934471+03:00", 
      "dateModified": "2017-05-25T17:28:04.934526+03:00", 
      "id": "ef780353c8004470add72739cb50fb3f"
    }
  ]
}

