PATCH /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/contracts/c711443e16b14269bcb6a28ba525d471?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2017-05-25T17:28:05.187777+03:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/d76c16815b504ab9b0b1fda1ba3d99ba?KeyID=561eda93&Signature=KL2YXgj6%2FYQpISacrmg1HkHil6Z%252Bqn%252BuooH4Hca3O9QPSxYm1utZH8VLx46pqzx%252BOMAUsEPll3HYVh1fN0WtBQ%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:04.579796+03:00", 
        "dateModified": "2017-05-25T17:28:04.579838+03:00", 
        "id": "13521a7c2d93476f96c0ec8e3b8b3feb"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/289f8a278eb644cb9f7d298afaae9b5c?KeyID=561eda93&Signature=2tXeY1giwOBC8mvhDecnmMgSwm5SwuJs06ahLwgZy41ztfH5NRjEqW1IswY8K1HmxvaKvBQi%252BP167x3%252BypAaCg%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:28:04.934471+03:00", 
        "dateModified": "2017-05-25T17:28:04.934526+03:00", 
        "id": "ef780353c8004470add72739cb50fb3f"
      }
    ], 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "08391d0984d74b1787545029fff9485f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2017-05-25T17:27:45.012376+03:00", 
      "endDate": "2018-05-25T17:27:45.012376+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-05-25T17:28:05.187777+03:00", 
    "date": "2017-05-25T17:28:05.425351+03:00", 
    "awardID": "96144c4198a54cac8649c4979444cd6b", 
    "id": "c711443e16b14269bcb6a28ba525d471", 
    "contractID": "UA-PS-2017-05-25-000001-1"
  }
}

