GET /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/bids/ddb0bdf5ee6a49f8b869c67f72f40b40?acc_token=a41cc5c3a51645d7a6aa0507ca6950d7 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "value": {
      "currency": "UAH", 
      "amount": 501.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-05-25T17:28:02.111574+03:00", 
    "qualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "owner": "broker", 
    "id": "ddb0bdf5ee6a49f8b869c67f72f40b40", 
    "participationUrl": "http://auction-sandbox.openprocurement.org/auctions/b0cb82074afe46c4a99deba3a188d456?key_for_bid=ddb0bdf5ee6a49f8b869c67f72f40b40"
  }
}

