POST /api/2.3/auctions?opt_pretty=1 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 2009
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "title": "футляри до державних нагород", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35
    }, 
    "auctionPeriod": {
      "startDate": "2017-06-08T17:27:45.012376"
    }, 
    "title_en": "Cases with state awards", 
    "value": {
      "currency": "UAH", 
      "amount": 500
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }, 
    "dgfDecisionDate": "2016-11-17", 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "ID", 
    "title_ru": "футляры к государственным наградам", 
    "dgfDecisionID": "219560", 
    "items": [
      {
        "classification": {
          "scheme": "CPV", 
          "id": "66113000-5", 
          "description": "Земельні ділянки"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "526e1391b40b4c12b06f3e5be44045f7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "mode": "test"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/3ed08ce601044ace8c7b7b419261b637

{
  "access": {
    "token": "cc48c923051943458ecb925486dc0940"
  }, 
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-PS-2017-05-25-000002", 
    "enquiryPeriod": {
      "startDate": "2017-05-25T17:27:59.798901+03:00", 
      "endDate": "2017-06-07T20:00:00+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "next_check": "2017-06-07T20:00:00+03:00", 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "kind": "general", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "title_en": "[TESTING] Cases with state awards", 
    "id": "3ed08ce601044ace8c7b7b419261b637", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:27:59.799337+03:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2017-05-25T17:27:59.799380+03:00", 
        "id": "e1b9eeffd8814a998c65cf27eab8e8ac"
      }
    ], 
    "title": "[ТЕСТУВАННЯ] футляри до державних нагород", 
    "dateModified": "2017-05-25T17:27:59.803448+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-05-25T17:27:59.798901+03:00", 
      "endDate": "2017-06-07T20:00:00+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-06-08T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "ID", 
    "date": "2017-05-25T17:27:59.798901+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "description": "Земля для військовослужбовців", 
        "id": "526e1391b40b4c12b06f3e5be44045f7", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "mode": "test", 
    "title_ru": "[ТЕСТИРОВАНИЕ] футляры к государственным наградам", 
    "awardCriteria": "highestCost"
  }
}

