GET /api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents/d7a894af9c7c46b191e25d056030b93a HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4ee12ff5d5dd4d6b8e7ac8d53d68f68b?KeyID=209755f5&Signature=YVUfgMbAj2wVaGng%252BDAAkO3Z2AVPi5IFQI8iiW5hXHkd2biM043qUJRP3KHN46fe%252BzunF9pu8JCjKK06HKYnDg%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:27:56.932661+03:00", 
    "previousVersions": [], 
    "documentType": "technicalSpecifications", 
    "dateModified": "2017-05-25T17:27:56.932707+03:00", 
    "id": "d7a894af9c7c46b191e25d056030b93a"
  }
}

