POST /api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents?acc_token=c44eee142e0f4760a4ba58a6fad3e472 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 127
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://virtial-data-room.com/id_of_room", 
    "title": "VDR for auction lot", 
    "documentType": "virtualDataRoom"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents/1161b8b85cad4e33b2dc3464cea9a10f

{
  "data": {
    "title": "VDR for auction lot", 
    "url": "http://virtial-data-room.com/id_of_room", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:27:57.325557+03:00", 
    "documentType": "virtualDataRoom", 
    "dateModified": "2017-05-25T17:27:57.325609+03:00", 
    "id": "1161b8b85cad4e33b2dc3464cea9a10f"
  }
}

