PUT /api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents/d0e5803ac10042e793e289a5c2b6a1fb?acc_token=c44eee142e0f4760a4ba58a6fad3e472 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 340
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/719127c91a1a4b2fbea5929c57d5efaf?KeyID=209755f5&Signature=bfeuXiiK%2BxiiiNoKvDIzFo57PCAGVR64n6I4t%2FgTez2FsZAwGnu0seya4g1RSvmfyIhfBnWc%2BDkuyoX2qwi3Bw%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/719127c91a1a4b2fbea5929c57d5efaf?KeyID=209755f5&Signature=j8HVhebqOejUJBbwYWv9QOadUGVhkD11tXlzyfeNX9WQxltxQcCkrkl3eyVig6M3Xx72oRjJhS5i7KrZhYdcAw%253D%253D", 
    "title": "AwardCriteria-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:27:57.080887+03:00", 
    "dateModified": "2017-05-25T17:27:57.194822+03:00", 
    "id": "d0e5803ac10042e793e289a5c2b6a1fb"
  }
}

