POST /api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents?acc_token=c44eee142e0f4760a4ba58a6fad3e472 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 338
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/2021d75680d34e788aa9f3218c5f9c97?KeyID=209755f5&Signature=lnMZsKS1A4z6HrHu9r%2FAo1e%2Feal8sDN6HRKyBE3Dv2rk4aJRKt9JRFTgp3t6RCO9f3NxBF67H2SxJ%2FcqrgZ1Cw%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents/d0e5803ac10042e793e289a5c2b6a1fb

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/2021d75680d34e788aa9f3218c5f9c97?KeyID=209755f5&Signature=N1JSln%2FfUNPXFY2zsco5HFhp2jRJz2wJYDGdzR4%252BUFe1UtQfKSdtOr8etAvbF72lBgZWv%252B6%252BUT%252BV3Dj%252BUcQJDg%253D%253D", 
    "title": "AwardCriteria.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:27:57.080887+03:00", 
    "dateModified": "2017-05-25T17:27:57.080934+03:00", 
    "id": "d0e5803ac10042e793e289a5c2b6a1fb"
  }
}

