GET /api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents HTTP/1.0
Authorization: Basic YnJva2VyOg==
Host: api-sandbox.ea.openprocurement.org


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": [
    {
      "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
      "url": "http://torgi.fg.gov.ua/prozorrosale", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:27:56.670192+03:00", 
      "documentType": "x_dgfPlatformLegalDetails", 
      "dateModified": "2017-05-25T17:27:56.670252+03:00", 
      "id": "0718db9fe65446a3ac7fffb3551b1e3f"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "description": "technical specification", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4ee12ff5d5dd4d6b8e7ac8d53d68f68b?KeyID=209755f5&Signature=YVUfgMbAj2wVaGng%252BDAAkO3Z2AVPi5IFQI8iiW5hXHkd2biM043qUJRP3KHN46fe%252BzunF9pu8JCjKK06HKYnDg%253D%253D", 
      "title": "Notice.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:27:56.932661+03:00", 
      "documentType": "technicalSpecifications", 
      "dateModified": "2017-05-25T17:27:56.932707+03:00", 
      "id": "d7a894af9c7c46b191e25d056030b93a"
    }, 
    {
      "hash": "md5:00000000000000000000000000000000", 
      "format": "application/pdf", 
      "url": "http://public.docs-sandbox.ea.openprocurement.org/get/719127c91a1a4b2fbea5929c57d5efaf?KeyID=209755f5&Signature=j8HVhebqOejUJBbwYWv9QOadUGVhkD11tXlzyfeNX9WQxltxQcCkrkl3eyVig6M3Xx72oRjJhS5i7KrZhYdcAw%253D%253D", 
      "title": "AwardCriteria-2.pdf", 
      "documentOf": "tender", 
      "datePublished": "2017-05-25T17:27:57.080887+03:00", 
      "dateModified": "2017-05-25T17:27:57.194822+03:00", 
      "id": "d0e5803ac10042e793e289a5c2b6a1fb"
    }
  ]
}

