PATCH /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 75
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "tenderPeriod": {
      "endDate": "2017-06-09T17:28:09.998900+03:00"
    }
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "procurementMethod": "open", 
    "auctionID": "UA-PS-2017-05-25-000001", 
    "enquiryPeriod": {
      "startDate": "2017-05-25T17:27:59.569797+03:00", 
      "endDate": "2017-06-07T23:59:50+03:00"
    }, 
    "submissionMethod": "electronicAuction", 
    "dgfDecisionDate": "2016-11-17", 
    "next_check": "2017-06-07T23:59:50+03:00", 
    "awardCriteria": "highestCost", 
    "dgfDecisionID": "219560", 
    "owner": "broker", 
    "id": "b0cb82074afe46c4a99deba3a188d456", 
    "documents": [
      {
        "title": "Місце та форма прийому заяв на участь в аукціоні та банківські реквізити для зарахування гарантійних внесків", 
        "url": "http://torgi.fg.gov.ua/prozorrosale", 
        "documentOf": "tender", 
        "datePublished": "2017-05-25T17:27:59.570223+03:00", 
        "documentType": "x_dgfPlatformLegalDetails", 
        "dateModified": "2017-05-25T17:27:59.570283+03:00", 
        "id": "e4efbf88435a487582b4c119a5c0970c"
      }
    ], 
    "title": "футляри до державних нагород", 
    "tenderAttempts": 1, 
    "procurementMethodDetails": "quick, accelerator=1440", 
    "dateModified": "2017-05-25T17:27:59.577396+03:00", 
    "status": "active.tendering", 
    "tenderPeriod": {
      "startDate": "2017-05-25T17:27:59.569797+03:00", 
      "endDate": "2017-06-07T23:59:50+03:00"
    }, 
    "auctionPeriod": {
      "shouldStartAfter": "2017-06-08T00:00:00+03:00"
    }, 
    "procurementMethodType": "dgfOtherAssets", 
    "dgfID": "219560", 
    "date": "2017-05-25T17:27:59.569797+03:00", 
    "minimalStep": {
      "currency": "UAH", 
      "amount": 35.0, 
      "valueAddedTaxIncluded": true
    }, 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CPV", 
          "description": "Земельні ділянки", 
          "id": "66113000-5"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "08391d0984d74b1787545029fff9485f", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 100.0, 
      "valueAddedTaxIncluded": true
    }, 
    "procuringEntity": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }
  }
}

