POST /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/cancellations?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 43
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "reason": "cancellation reason"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/cancellations/cd5555cb65f8400f858ab4dc7f069a11

{
  "data": {
    "date": "2017-05-25T17:28:05.819216+03:00", 
    "status": "pending", 
    "reason": "cancellation reason", 
    "cancellationOf": "tender", 
    "id": "cd5555cb65f8400f858ab4dc7f069a11"
  }
}

