PUT /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents/8de16b471d1a481d8c26ef6876e3da0b?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 346
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b65535c4bc074b72a60f62acb82472f4?KeyID=561eda93&Signature=NuviaFqtubop5%2FiWC2v3EIkDct84gWGrCgEt9jnhZjLdEbWMe5jS9Bu2kthHceV8%2FJA6SQ%2B%2FH2ouTA%2Br%2FJkRCA%3D%3D", 
    "title": "AwardCriteria-2.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/b65535c4bc074b72a60f62acb82472f4?KeyID=561eda93&Signature=QjWyizp6j1aJUgyNi0lqSP9LBTCixti9L1VNVP7mqK7TLtRxNl8ufSwa7Zygg%2Fj%252Bu99v7GHR6rykbXWCkYv7AQ%253D%253D", 
    "title": "AwardCriteria-2.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:28:00.316280+03:00", 
    "dateModified": "2017-05-25T17:28:00.447454+03:00", 
    "id": "8de16b471d1a481d8c26ef6876e3da0b"
  }
}

