POST /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 434
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "title": "first_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e281146b2c1749f08360f1e8bdb82ba2?KeyID=561eda93&Signature=GbESqOThZFZSgMyjRzPKV%2FuQ7Kc%2F%2FqJHK%2Fyzm9qOkS46M5QeOxR5r4hqRZw38eoeDkSBEdHmJYRIRlPSQ2sxBA%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents/3fd6f0ea761440ca82f5c6c002ab9779

{
  "data": {
    "index": 1, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "First illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/e281146b2c1749f08360f1e8bdb82ba2?KeyID=561eda93&Signature=5wz2KBsPr0Izti7DjUBJsOpdiiRfPv13vZI7By3uMdxoJDLPSp%2F1xccfksXFNM1r5T%2FvLEVHHiiBG2EBX4woDA%253D%253D", 
    "title": "first_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:28:00.565678+03:00", 
    "documentType": "illustration", 
    "dateModified": "2017-05-25T17:28:00.565725+03:00", 
    "id": "3fd6f0ea761440ca82f5c6c002ab9779"
  }
}

