POST /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 430
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "title": "second_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c6da3fd87c57460ea3e698a31a2a1aa1?KeyID=561eda93&Signature=usnfL4%2BqUEpog2uSGV23IpQBrfnsOUgA61acJblblmfiteGn7l3ljWdpFueSPcBfkmi9Ny4hojAmxFfLxCijBw%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents/7ede76dd3ab94e8ca093c4ebb62ce1bd

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Second illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/c6da3fd87c57460ea3e698a31a2a1aa1?KeyID=561eda93&Signature=qk0YGoVQ5GmtgBgga4GZ1Fu%252BaS3nj40gW8SvaRxRcUEnxl2iSkAfh3fHzeaCf7p0RYV5GtIbxTeTfcFMehrTDA%253D%253D", 
    "title": "second_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:28:00.698675+03:00", 
    "documentType": "illustration", 
    "dateModified": "2017-05-25T17:28:00.698721+03:00", 
    "id": "7ede76dd3ab94e8ca093c4ebb62ce1bd"
  }
}

