POST /api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents?acc_token=c44eee142e0f4760a4ba58a6fad3e472 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 416
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "title": "Notice.pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4ee12ff5d5dd4d6b8e7ac8d53d68f68b?KeyID=209755f5&Signature=mA6SSbsoa%2F4slkhwUwBeMCmC9FjBzaJ%2Fo9noaDIMWAYu2Zx73U1GdR7ub%2B8v5QUPyq7bvKIAlcKfNRPlYc3PAw%3D%3D", 
    "format": "application/pdf", 
    "documentType": "technicalSpecifications"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b4642b238000446da633ee7ddceaf888/documents/d7a894af9c7c46b191e25d056030b93a

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "description": "technical specification", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4ee12ff5d5dd4d6b8e7ac8d53d68f68b?KeyID=209755f5&Signature=YVUfgMbAj2wVaGng%252BDAAkO3Z2AVPi5IFQI8iiW5hXHkd2biM043qUJRP3KHN46fe%252BzunF9pu8JCjKK06HKYnDg%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:27:56.932661+03:00", 
    "documentType": "technicalSpecifications", 
    "dateModified": "2017-05-25T17:27:56.932707+03:00", 
    "id": "d7a894af9c7c46b191e25d056030b93a"
  }
}

