POST /api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents?acc_token=b8246a8ec6124df0a4a96ef8d975262d HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 428
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "title": "third_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bc4490ed8c1f4d6daa18795ea1c78208?KeyID=561eda93&Signature=dYji1WEctPUB2WjaJN42V7nkEco%2FeDlx4RJWOCOacc2fMwKZwngyZtUjrlcyVaew83AQcSkvuTjsXUb266e4DQ%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/b0cb82074afe46c4a99deba3a188d456/documents/25e01f0d8d9d4d568ad6796c825272d3

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/bc4490ed8c1f4d6daa18795ea1c78208?KeyID=561eda93&Signature=OENTefhpCFK6qCBNcMY%252B%2F1gGtk1fqAUOR8wYRJdnpHRAaroDRaTtnlDr5bEJxuYz%2FJ9I46a2KmwswPifKQD%2FCg%253D%253D", 
    "title": "third_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-05-25T17:28:00.802456+03:00", 
    "documentType": "illustration", 
    "dateModified": "2017-05-25T17:28:00.802509+03:00", 
    "id": "25e01f0d8d9d4d568ad6796c825272d3"
  }
}

